### ISSUE TITLE
Rake task ignoring the user property

### ISSUE THREAD

**Issue by sonyakc** [hipchat/hipchat-rb#105]
The rake test (actually the room.send method) is ignoring the user property and instead always using the user associated with the auth token. Is this expected behavior? The server is basically ignoring the user options value and not defaulting to 'whoami' as per the comment in hipchat.yml. We're trying to use one auth token and have the sender by the person executing the script.

**Comment by rhinon** [comment]
I'm confused, are we supposed to be passing the username + token in as part of the `HipChat::Client` constructor?  As the documentation says, I've been passing in just the token and trying to pass the username through `send()` and am not seeing the correct username in the chat room.

**Comment by zsiddique** [comment]
@tfwright you are correct, V2 does not require the from param, it uses the user associated with the token. 

@sonyakc if you want to use API v2 token its best that each user uses their own HipChat token.

@rhinon No you just need the token.
