### ISSUE TITLE
hipchat_announce announces to room even if set to false

### ISSUE THREAD

**Issue by alexfarrill** [hipchat/hipchat-rb#107]
Not sure exactly what the intended behavior of this is, but it seems to announce to the room even if it's set to false

**Comment by radarek** [comment]
This was completely intentional. Please, read hipchat API documentation for sending messages: https://www.hipchat.com/docs/apiv2/method/send_room_notification Look for option `notify`.

**Comment by l8nite** [comment]
@arkadyan This change has broken our existing deployment scripts - the README says that announce should "notify users". Now, it doesn't send any hipchat message at all.

**Comment by arkadyan** [comment]
@l8nite Then how do we control whether or not the task should send a message? Reverting this would remove critical functionality for us unless there is some other method for controlling that.

**Comment by l8nite** [comment]
@arkadyan I've updated my PR to include a :hipchat_enabled setting that preserves your intended use case.

**Comment by arkadyan** [comment]
@l8nite Great, thanks! I think hopefully this makes the purpose of each setting more clear as well.
