### ISSUE TITLE
Should v2 become the new default api version?

### ISSUE THREAD

**Issue by joraff** [hipchat/hipchat-rb#109]
Now that all API v1 use is discouraged, I think that v2 should become default and v1 use should be explicitly requested.

`client = HipChat::Client.new(api_token)` _uses API v2_
`client = HipChat::Client.new(api_token, api_version: 'v1')` _uses API v1_

Happy to do a PR

**Comment by rberrelleza** [comment]
https://github.com/hipchat/hipchat-rb/pull/191 will cover this
