### ISSUE TITLE
UnknownResponseCode: Unexpected 400 for room `room` when using API v2

### ISSUE THREAD

**Issue by seandc** [hipchat/hipchat-rb#123]
When I attempt to use API v2, I get the error: `UnknownResponseCode: Unexpected 400 for room 'room'`

I change my token to an API v2 access token and instantiate my client with the `:api_version` option set to 'v2':
```ruby
HipChat::Client.new(token, :api_version => 'v2' )
```

Any idea what the issue might be?  Do any other changes need to happen when switching to API v2?

**Comment by carlhoerberg** [comment]
When using v2 i'm getting `HipChat::Unauthorized: Access denied to room 'x' `, but not with v1...

**Comment by seandc** [comment]
@carlhoerberg Did you change your token to be an API v2 token?

**Comment by carlhoerberg** [comment]
No I guess not. Will API v1 be deprecated soon? It's so much easier to use than oauth and web autentication..

**Comment by marksterxxx** [comment]
Hi, I'm using API v2 token and get the same error as @carlhoerberg ,
```ruby
client = HipChat::Client.new(HIPCHAT_CONFIG["tokenv2"], :api_version => 'v2')
client['x'].send('username', 'I talk')
```
Unauthorized: Access denied to room 'x'

GET request to api.hipchat.com/v2/room?auth_token=xxxxxxxx&auth_test=true gives me
```json
{"success": {"code": 202, "message": "This auth_token has access to use this method.", "type": "Accepted"}}
```

**Comment by chulkilee** [comment]
I had to use user-level API token for V2 API. group-level API tokens only worked with V1 API.

**Comment by marksterxxx** [comment]
nevermind... it works now..

**Comment by seandc** [comment]
I resolved my issue.  If the 'notify' option was set to `nil` in v1 when sending a message, everything worked fine.  In v2, setting 'notify' to `nil` causes the server to return 400.  This issue can be closed from my perspective, but I'm not sure if other people are still having problems.

**Comment by rmanalan** [comment]
Just testing something... ignore...
