### ISSUE TITLE
Wrong usage of hipchat_announce option

### ISSUE THREAD

**Issue by radarek** [hipchat/hipchat-rb#131]
Usage of `hipchat_announce` option is completely wrong, at least for my understanding. I guess the intention for this option was to use as "notify" option in hipchat API for sending message. Here is description from docs page https://www.hipchat.com/docs/apiv2/method/send_room_notification:
```
notify	
Whether this message should trigger a user notification (change the tab color, play a sound, notify mobile phones, etc). Each recipient's notification preferences are taken into account.
Defaults to false.
```

Basically when this option is set to false messages should be still send but hipchat will not notify users about it.  Current behaviour is that message won't be set at all which is completely broken.

It was broken by merging pull https://github.com/hipchat/hipchat-rb/pull/126 Please, revert it.

**Comment by l8nite** [comment]
Thanks @radarek for filing this, I commented on #107 as well -- you are correct.

**Comment by radarek** [comment]
Thank you!
