### ISSUE TITLE
HTTParty 0.13.4 breaks hipchat-rb 1.5.1

### ISSUE THREAD

**Issue by shawnpyle** [hipchat/hipchat-rb#135]
Just attempted to integrate hipchat into rails project and got the following error:
```
NameError: uninitialized constant HTTParty::HashConversions::ERB
from /usr/local/var/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/httparty-0.13.4/lib/httparty/hash_conversions.rb:33:in `normalize_param'
```
and it's related to this issue: https://github.com/jnunemaker/httparty/issues/398

Looks like you'll need to tie the gem to a version.

**Comment by JacobEvelyn** [comment]
+1

**Comment by rberrelleza** [comment]
It looks like httparty already [fixed the issue](https://github.com/jnunemaker/httparty/pull/399) on their side. Could you please let me know if it's still happening on the latest version?
