### ISSUE TITLE
hipchat_announce setting does nothing for Capistrano

### ISSUE THREAD

**Issue by nick-desteffen** [hipchat/hipchat-rb#158]
When I set `hipchat_announce` to false notifications still show up in our chat rooms.

**Comment by schlick** [comment]
Be aware of the difference between `hipchat_enabled` and `hipchat_announce`. Setting `hipchat_enabled` to `false` stops any messages from being sent to hipchat which is great when you're testing stuff with capistrano and wish to turn hipchat messages temporarily. Setting `hipchat_announce` to `false` will still continue to post messages into a hipchat room but it won't trigger a user notification for that message eg change the tab color, play a sound, notify mobile phones. `hipchat_announce` is the `notify` option from https://developer.atlassian.com/hipchat/guide/sending-messages
