### ISSUE TITLE
notify option for private message?

### ISSUE THREAD

**Issue by cpanderson** [hipchat/hipchat-rb#166]
It doesn't seem I can override `:notify => false` when sending a private message using...

`client.user(email).send(message)`

...as per this documentation https://www.hipchat.com/docs/apiv2/method/private_message_user

Please advise. Thanks

**Comment by flyinbutrs** [comment]
Should be fixed by PR #168 
Not sure when that will be released to rubygems.com though.

**Comment by rberrelleza** [comment]
It's released as of this morning, thanks!

**Comment by cpanderson** [comment]
Excellent! Thank you!

**Comment by cwitthaus** [comment]
@cpanderson were you able to get the notify to work when sending a private message? The messages are sending fine for me with `send('I can send private messages!', {notify: true})` but I'm not notified.
