### ISSUE TITLE
Notifications for private messages failing

### ISSUE THREAD

**Issue by JCSHoosier** [hipchat/hipchat-rb#178]
Currently using the Hipchat gem 1.5.3 but have not been able to override the notify parameter to be true. We manually changed the locally installed gem to mirror the code change in #170 and it worked. Any updates on when this will be packaged for release?

CC: @NaomiReeves

**Comment by JSenitza** [comment]
After a bit of troubleshooting we were able to change the notify parameter, but it required us to set the message format variable as well. We still would be interested in an update as to when change #170 will be released.

**Comment by rberrelleza** [comment]
I was released on 1.5.4, earlier today.
