### ISSUE TITLE
Should support for ruby 1.9 be dropped?

### ISSUE THREAD

**Issue by rberrelleza** [hipchat/hipchat-rb#183]
Some of the dependencies are starting to drop support for Ruby 1.9, should the HipChat library do the same in favor of being able to use newer deps?

**Comment by gabrielmdeal** [comment]
I say drop 1.9.3 support.  It was end of lifed nearly two years ago.

The hipchat-rb 1.9.3 build broke in Dec due to a gem dropping 1.9.3 support (#182).  And it is broken again now for the same reason (#187).

**Comment by rberrelleza** [comment]
I agree. I'll schedule some time during to week to remove the 1.9.3 dependencies, and to rev up the major release version.
