### ISSUE TITLE
Room methods ignore hash arguments

### ISSUE THREAD

**Issue by jfitisoff** [hipchat/hipchat-rb#185]
It looks like some of the room methods end up ignoring hash arguments. 

Steps:
- Add some debug output to Room#history to output processed options.
- Initialize a client.
- Call client[ROOM].history with some options like date and max-results.

Expected: Hash args passed in by user override the default args.
Actual:      User args are ignored. Default args are used.

Created https://github.com/hipchat/hipchat-rb/pull/184 to show how I worked around this locally

**Comment by rberrelleza** [comment]
Closing since #184 fixed the issue
