### ISSUE TITLE
Create user?

### ISSUE THREAD

**Issue by krogebry** [hipchat/hipchat-rb#96]
Am I missing something here, or is there really no way to create new users via this lib?  I'm going to take a crack at building the functionality and see where I end up, unless, of course someone corrects me on this.

**Comment by rberrelleza** [comment]
You're right, there's no functionality to create a user (facepalm). Would appreciate a PR if you got around to build the functionality.

**Comment by LukeSettle** [comment]
Did this just get implemented? I see the create_user method in the client file, but when I updated the gem it does not seem to be there.

**Comment by rberrelleza** [comment]
Yes, it was merged about two weeks ago (https://github.com/hipchat/hipchat-rb/commit/8b08455295ba62adc97476802baade27f897bdf2). Haven't published a new version yet, I'll do it this week so this functionality is available.
